In [2]:
import numpy as np

In [2]:
# Question 1 : Import numpy as np and see the version

print(np.__version__)


1.26.2


In [ ]:
# Question 2 : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr0 = np.arange(10)
# array = np.arange(1, 11)  # start and stop
# array = np.arange(1, 10, 2)  # In steps of 2
print(arr0)

In [ ]:
# Question 3: Create a 3×3 numpy array of all True’s

# arr = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
arr1 = np.full((3, 3), True, dtype=bool)
print(arr1)

# or
# np.full((9), True, dtype=bool).reshape(3,3)

# or
# np.ones((3,3), dtype=bool)

# or
# np.ones((9), dtype=bool).reshape(3,3)

In [ ]:
# Question 4: Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

arr2 = np.arange(10)

arr3 = []
for arr in arr2:
    if arr % 2 != 0:
        arr3.append(arr)
print(arr3)

# or
# arr[arr % 2 == 1]

In [ ]:
# Question 5: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr4 = np.arange(10)

# for arr in arr4:
#     if arr % 2 != 0:
#         arr4[arr] = -1
# print(arr4)

arr4[arr4 %2 == 1] = -1
arr4


In [9]:
# Question 6: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr5 = np.arange(10)

out = arr5.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr5

Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Question 7: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

arr6 = np.arange(10)
print(arr6)

arr7 = np.resize(arr6,(2,5))
print(arr7)

arr8 = arr6.reshape(2,5)
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
# Question 8: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1) # -1 indicates that choose the cols automatically.
b = np.repeat(1, 10).reshape(2,-1) 

c = np.vstack([a,b]) # vstack is vertical stack
c



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
# Question 9: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b]) # hstack is for horizontal stack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [48]:
# Question 10: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

np.hstack((np.repeat(a, 3), np.tile(a, 3)))

# repeat = repeates the each element that many times
# tile = repeates the whole array that many times


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [50]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
c

array([2, 4])

In [52]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [53]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [54]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [58]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.
# Input:

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
#> 5

# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def pair_max(x, y):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(x, y)

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [59]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

Original array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])