In [1]:
import numpy as np

In [2]:
# Question 1 : Import numpy as np and see the version

print(np.__version__)


1.26.2


In [ ]:
# Question 2 : Create a 1D array of numbers from 0 to 9
# Output : #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr0 = np.arange(10)
# array = np.arange(1, 11)  # start and stop
# array = np.arange(1, 10, 2)  # In steps of 2
print(arr0)

In [ ]:
# Question 3: Create a 3×3 numpy array of all True’s

# arr = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
arr1 = np.full((3, 3), True, dtype=bool)
print(arr1)

# or
# np.full((9), True, dtype=bool).reshape(3,3)

# or
# np.ones((3,3), dtype=bool)

# or
# np.ones((9), dtype=bool).reshape(3,3)

In [ ]:
# Question 4: Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

arr2 = np.arange(10)

arr3 = []
for arr in arr2:
    if arr % 2 != 0:
        arr3.append(arr)
print(arr3)

# or
# arr[arr % 2 == 1]

In [ ]:
# Question 5: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr4 = np.arange(10)

# for arr in arr4:
#     if arr % 2 != 0:
#         arr4[arr] = -1
# print(arr4)

arr4[arr4 %2 == 1] = -1
arr4


In [9]:
# Question 6: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr5 = np.arange(10)

out = arr5.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr5

Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Question 7: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

arr6 = np.arange(10)
print(arr6)

arr7 = np.resize(arr6,(2,5))
print(arr7)

arr8 = arr6.reshape(2,5)
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
# Question 8: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)

a = np.arange(10).reshape(2,-1) # -1 indicates that choose the cols automatically.
b = np.repeat(1, 10).reshape(2,-1) 

c = np.vstack([a,b]) # vstack is vertical stack
c



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
# Question 9: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


# Solution:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b]) # hstack is for horizontal stack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [48]:
# Question 10: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

np.hstack((np.repeat(a, 3), np.tile(a, 3)))

# repeat = repeates the each element that many times
# tile = repeates the whole array that many times


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [50]:
# Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)
c

array([2, 4])

In [52]:
# Question: From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [53]:
# Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [54]:
# Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [58]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.
# Input:

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
#> 5

# Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def pair_max(x, y):
    """Get the element-wise maximum of two arrays"""
    return np.maximum(x, y)

pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [64]:
# Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)

arr[:, [0, 1]] = arr[:, [1, 0]]
arr

# print("\nModified array")
# arr[:, [1,0,2]]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [5]:
# Question: Swap rows 1 and 2 in the array arr:

# Input: 

arr = np.arange(9).reshape(3,3)
print('Original array')
print(arr)

# Solution

print("\nModified array")
arr[[1,0,2],:]

Original array

Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [12]:
# Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)

# Solution
arr[::-1,:] #slicing: start, stop, order 


Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
# Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

# Solution

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

In [7]:
# Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Solution:

rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[5.30283199, 8.02742637, 9.38764749],
       [8.02648298, 8.62390517, 7.08976609],
       [6.61684815, 6.00036246, 8.27568298],
       [9.20013111, 6.5189006 , 5.9653867 ],
       [6.26530406, 9.76150802, 9.81043953]])

In [8]:
# Question: Print or show only 3 decimal places of the numpy array rand_arr.

# Input: rand_arr = np.random.random((5,3))

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.743, 0.701, 0.269],
       [0.461, 0.198, 0.907],
       [0.433, 0.581, 0.481],
       [0.916, 0.698, 0.429],
       [0.531, 0.676, 0.937]])

In [10]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)

# Input: 
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)
print(rand_arr)

np.set_printoptions(suppress=True)
rand_arr

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


array([[0.001, 0.   , 0.   ],
       [0.001, 0.   , 0.   ],
       [0.001, 0.001, 0.   ]])

In [12]:
# Question: Limit the number of items printed in python numpy array a to a maximum of 6 elements.

num_arr = np.arange(10)
print(num_arr[:6])

# np.set_printoptions(threshold=6)

[0 1 2 3 4 5]


In [ ]:
# Question: Print the full numpy array a without truncating.

# Input: np.set_printoptions(threshold=6)
# a = np.arange(15)
# a

# Output: a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution

a = np.arange(15)


np.set_printoptions(threshold=15)
a

In [14]:
# Question: Import the iris dataset keeping the text intact.

# Solution:
# iris_data = np.genfromtxt('../input/iris/Iris.csv', delimiter=',', skip_header=1, 
#                           usecols = [0,1,2,3,4,5], dtype = object)
# iris_data

In [16]:
# Question: Find the mean, median, standard deviation of iris's sepallength (1st column)

# iris_data = np.genfromtxt('../input/iris/Iris.csv', delimiter=',', skip_header=1, usecols = [1])

# print('Mean', np.mean(iris_data))
# print('Median', np.median(iris_data))
# print('Standard Deviation', np.std(iris_data))

In [17]:
# How to normalize an array so the values range exactly between 0 and 1?
# Example array
arr = np.random.random((5, 3)) * 10  # Array with values between 0 and 10

# Normalize the array
arr_normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original Array:\n", arr)
print("\nNormalized Array:\n", arr_normalized)


Original Array:
 [[5.751 8.913 2.092]
 [1.853 1.084 2.197]
 [9.786 8.117 1.719]
 [8.162 2.741 4.317]
 [9.4   8.176 3.361]]

Normalized Array:
 [[0.536 0.9   0.116]
 [0.088 0.    0.128]
 [1.    0.808 0.073]
 [0.813 0.19  0.372]
 [0.956 0.815 0.262]]


In [21]:
# Question: How to insert values at random positions in an array?

a = np.arange(10)
b = np.arange(20,30,1)

ran_position = np.random.randint(5,100)
ran_position


85